from __future__ import annotations

from enum import Enum

from .event_types import EventType

DEFAULT_SHIELD_FIRE_MAPPING_MULTIPLIER = 0.5
DEFAULT_MIN_COOLDOWN = 1.0
DEFAULT_MIN_COOLDOWN_ABSOLUTE = 0.5
DEFAULT_TIME_PRECISION = 0.1
DEFAULT_MAX_EVENTS = 10_000

PROTOCOL_VERSION = "v1.0"


class SimulationErrorCode(str, Enum):
    CONFIG_VALIDATION_FAILED = "CONFIG_VALIDATION_FAILED"
    MISSING_UNIT_CONFIG = "MISSING_UNIT_CONFIG"
    INVALID_NUMERIC_VALUE = "INVALID_NUMERIC_VALUE"
    SIMULATION_OVERFLOW = "SIMULATION_OVERFLOW"
    INTERNAL_ENGINE_ERROR = "INTERNAL_ENGINE_ERROR"


EVENT_PRIORITY = {
    EventType.ATTACK: 10,
    EventType.PERIODIC_APPLY: 15,
    EventType.DAMAGE: 20,
    EventType.PERIODIC_TICK: 25,
    EventType.PERIODIC_EXPIRE: 26,
    EventType.BUFF_APPLY: 30,
    EventType.BUFF_EXPIRE: 31,
    EventType.COOLDOWN_RESET: 35,
    EventType.COOLDOWN_MODIFY: 35,
}
